### PR TITLE
Moppy adapted to work on STM32 for Arduino

### PR DESCRIPTION
**Pull request by DanielIvory**
Inspired by MrSolidSnake745 who ported Moppy to the Maple Mini micro controller which runs faster than the Arduino uno. Code was modified and tested on a STM32F103C8T6 "Blue Pill" which can be gotten for very cheap, but do not have USB bootloaders by default.
Care is needed when dealing with the STM32F103C8T6 or other similar controllers as many pins are not 5V tolerant. Exactly 8 drives can be run off a standard "Blue Pill".
Shift register and L298N functionality are not added as of yet.

### CODE REVIEW

**Comment by SammyIAm** [comment]
It's a little hard to tell from the diff, but are all the changes just in `FloppyDrives.cpp`?  If so, I think it might be best to just create a `FloppyDrivesSTM32` as a new instrument rather than duplicate all the rest of the code in a new src folder.

If I've missed some subtle differences in the other files it will be more challenging, but I'd still rather work on a solution that involves keeping code duplication to a minimum.

**Comment by Danman218** [comment]
The STM32 utilizes built-in timer libraries unlike Arduino which needs the `Timer1` library.
In my experiences, even if not included, the other `moppyInstrument` child classes are still attempted to be compiled. Since `Timer1` is still mentioned in the child class files, it throws an error since it is not compatible on STM32.

My solution was to recreate the the entire Arduino-end code and omit anything in the original Arduino style of code.

I apologize in advance if I am not very professional with GitHub. I have been a long-term follower of this project, but only now am getting into contributing.

**Comment by SammyIAm** [comment]
No apologies required, and I definitely appreciate the contribution!

My concern is that going forward if, for example, someone adds some additional note period calculations or adds a new message type, that they'll have to do it twice (once in the base code and once in the STM32 code).

The Timer1 library definitely poses a challenge.  Off hand I can only think of two options:
1. Forking the code (instead of duplicating it).  The downside is anyone wanting to use an STM32 would need to checkout a different branch, and changes in mainline would still need to be merged down into the STM32 branch.  But merging changes would be a lot easier than having to make them twice.
1. There's *got* to be some way to selectively compile/include files or libraries in a C/C++ project.  However I'm pretty new to C++ so I don't know what it is.  If anyone else tracking this has any ideas I'm all ears.  Otherwise I'll do a bit of reading and see if I can come up with some sort of option.

I'd really like to get these changes included some how because I know many people are trying to use different hardware options.  Just gotta figure out a way to do it that doesn't cause too much trouble for the core Arduino base.

**Comment by SammyIAm** [comment]
What IDE do you use to upload code to the STM?

**Comment by dmadison** [comment]
Normal practice is to use preprocessor statements (e.g. `#ifdef`) to tweak the code to build for different platforms. Only trick is that for the Arduino IDE you can't ignore source (cpp) files even if they're unused, so for example you can't add an STM32 library with a source file to your sketch folder and try to build for an Arduino Uno.

**Comment by SammyIAm** [comment]
@dmadison , I'm hoping in this case that if STM generally uses a different IDE (not the Arduino IDE) then we can still have the STM files sitting around without breaking the Arduino build (since the breaks are caused by Timer1 not working for the STM build).

So we only need the ability to ignore things during the STM build.  If not, it looks like there might be some cpp flags we could use to ignore/include certain things (which can be set in the Arduino IDE)

**Comment by Danman218** [comment]
I believe the Arduino IDE is commonly used by STM32 beginners (such as myself) and other IDEs are used for more advanced users.

I think I know of a way to go around compiling the different timers now that you mention flags. Would involve a bit of modification to the other instrument classes. Will test and update.

**Comment by Danman218** [comment]
The problem that keeps surfacing is the fact that Arduino goes down any directories in the same directory as the .ino file and tries to compile them. On the other hand, when trying to use something such as a `#if` in order to toggle a `#include` the IDE will simply ignore it and include the library or header file anyway.

So if I try and exclude the TimerOne library in each instrument class when compiling for STM32, it still compiles the TimerOne and throws the error.
On the other hand, if I try to compile for Arduino and exclude the entire FloppyDriveSTM32 files (because Arduino doesn't play well with its pin names) the STM32 files still get compliled and errors are thrown.

I tried looking into how to avoid this but many of the solutions mentioned were to just use another IDE.

As this is a problem of the Arduino IDE, I would be willing to retract all this so as to maintain your organization but defeat the goal of having additional hardware working with as few branches as possible.

**Comment by SammyIAm** [comment]
This is... A bit messy, but if you change the file extension (or add, like,
.STM32), would the Arduino ignore it?  It would mean special instructions
for STM users to rename the files, but might be acceptable.

Thoughts?  Is that too inconvenient?

**Comment by Danman218** [comment]
I do agree it is a bit messy.
To get most STM chips to work, one already has to deal with serial programming, I don't think that it would be too much to ask to rename a file or two.

You could leave the Moppy32 directory  but with just the FloppyDrivesSTM32 files in it and have STM users copy the two files over to the MoppyInstruments directory rather than rename.

As I have it in my test environment now, all that changes is the presence of the two STM32 files and a comment block which toggles between STM32 and Arduino, all the original Arduino files can remain.

**Comment by SammyIAm** [comment]
Actually, yeah, I like the separate folder that just needs copying instead
of renaming.  The blocks in the main code can just stay commented out with
instructions on moving the files.

**Comment by dmadison** [comment]
>On the other hand, when trying to use something such as a #if in order to toggle a #include the IDE will simply ignore it and include the library or header file anyway.

This is not true. The Arduino IDE does not override the preprocessor statements:

```c++
#if 0
#include "Foo.h"  // No compilation error even with no Foo.h
#endif

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

The IDE *does* do recursive compilation, so you can't have source files in the sketch folder that won't compile. But it is absolutely possible to exclude things, including header includes, using the preprocessor.

**Comment by ComputerSongs** [comment]
Hi. I am very interested in the subject, and I hoped to manage to modify the code of Shiftregister.cpp, since I see that it is not very complicated, and I would like you to check if this is ok, I'm sorry, I do not know how to attach the file:

```
/*
 * ShiftRegister.cpp
 *
 * Output for controlling a single device that uses shift registers, one
 * bit for each note.  E.g. Xylophones or drums
 */
#include "ShiftRegister.h"
#include "MoppyInstrument.h"

// Define pins for connection to shift registers
#define DATA_PIN PB12
#define SHIFT_CLOCK_PIN PB13
#define LATCH_PIN PB14
// #define MASTER_CLEAR_PIN PB15
// #define OUTPUT_ENABLE_PIN PA8

// First and last supported notes (any notes outside this range will be ignored, first note will be
// indexed as zero for shifting
#define NUM_NOTES 24
const uint8_t FIRST_NOTE = 79;
const uint8_t LAST_NOTE = FIRST_NOTE + (NUM_NOTES-1);

#define SHIFT_TIMER_RESOLUTION 1000 //Microsecond resolution for starting and ending notes

// The velocity of the incoming notes will adjust the pulse length from MIN_PULSE_TICKS to MIN_PULSE_TICKS + PULSE_TICKS_RANGE
#define MIN_PULSE_TICKS 10 // Minimum length of "on" pulse for each bit in ticks (e.g. RESOLUTION * PULSE_TICKS microseconds)
#define PULSE_TICKS_RANGE 60 // Maximum number of ticks to add to MIN_PULSE_TICKS for maximum velocity

#define SHIFT_DATA_BYTES 3
uint8_t ShiftRegister::shiftData[SHIFT_DATA_BYTES]; // 8*3 = 24
uint8_t ShiftRegister::activeTicksLeft[NUM_NOTES];

boolean ShiftRegister::shouldShift = false; // When true, a shift will occur during the next tick

void ShiftRegister::setup() {

  // Prepare pins
  pinMode(DATA_PIN, OUTPUT);
  pinMode(SHIFT_CLOCK_PIN, OUTPUT);
  pinMode(LATCH_PIN, OUTPUT);

  // Don't enable these unless you plan to use them!
  //pinMode(MASTER_CLEAR_PIN, OUTPUT);
  //pinMode(OUTPUT_ENABLE_PIN, OUTPUT);

  pinMode(PC13, OUTPUT); // Built-in LED for blinking


  // With all pins setup, let's do a first run reset
  zeroOutputs();
  delay(500); // Wait a half second for safety

  // Setup timer to handle interrupts for floppy driving
  driveTimer.pause();
  driveTimer.setPeriod(SHIFT_TIMER_RESOLUTION);
  driveTimer.setChannel1Mode(TIMER_OUTPUT_COMPARE);
  driveTimer.setCompare(TIMER_CH1, 1);
  driveTimer.attachCompare1Interrupt(tick);
  driveTimer.refresh();
  driveTimer.resume();

}


//
//// Message Handlers
//

// Handles system messages (e.g. sequence start and stop)
void ShiftRegister::systemMessage(uint8_t command, uint8_t payload[]) {
  switch(command) {
      // NETBYTE_SYS_PING is handled by the network adapter directly
    case NETBYTE_SYS_RESET: // System reset
      zeroOutputs();
      break;
    case NETBYTE_SYS_START: // Sequence start
      // Nothing to do here yet
      break;
    case NETBYTE_SYS_STOP: // Sequence stop
      zeroOutputs();
      break;
  }
}

// Handles device-specific messages (e.g. playing notes)
void ShiftRegister::deviceMessage(uint8_t subAddress, uint8_t command, uint8_t payload[]) {
  switch(command) {
    case NETBYTE_DEV_RESET: // Reset
      zeroOutputs(); // SubAddress unimportant here since we only have one
      break;
    case NETBYTE_DEV_NOTEON: // Note On
      if (payload[0] >= FIRST_NOTE && payload[0] <= LAST_NOTE) {
        outputOn(payload[0] - FIRST_NOTE);
        activeTicksLeft[payload[0] - FIRST_NOTE] = MIN_PULSE_TICKS + ((payload[1] * PULSE_TICKS_RANGE)/127);
        shouldShift = true;
      }
      break;
    case NETBYTE_DEV_NOTEOFF: // Note Off
      // Ignore these, the solenoids are pulsed the same length for all notes
      break;
    case NETBYTE_DEV_BENDPITCH: //Pitch bend
      // Ignore these, we can't bend pitch
      break;
  }
}

//
//// Floppy driving functions
//

/*
Called by the timer interrupt at the specified resolution.  Because this is called extremely often,
it's crucial that any computations here be kept to a minimum!
 */
void ShiftRegister::tick()
{
  for (byte n = 0; n < NUM_NOTES; n++) {
    if (activeTicksLeft[n] > 0) {
      if (--activeTicksLeft[n] == 0) {
        outputOff(n);
        shouldShift = true;
      }
    }
  }

  if (shouldShift) {
    shouldShift = false;
    shiftAllData();
  }
}

////
// UTILITY FUNCTIONS
////

//Not used now, but good for debugging...
void blinkLED(){
  digitalWrite(PC13, LOW); // set the LED on
  delay(250);              // wait for a second
  digitalWrite(PC13, HIGH);
}


////
// Shifting and bitsetting functions
////

void ShiftRegister::shiftAllData()
{
  digitalWrite(LATCH_PIN, LOW);
  for (int i=SHIFT_DATA_BYTES-1;i>=0;i--){
    shiftOut(DATA_PIN, SHIFT_CLOCK_PIN, MSBFIRST, shiftData[i]);
  }
  digitalWrite(LATCH_PIN, HIGH);
}

void ShiftRegister::outputOn(byte outputNum){
  bitSet(shiftData[outputNum/8],outputNum%8);
}

void ShiftRegister::outputOff(byte outputNum){
  bitClear(shiftData[outputNum/8],outputNum%8);
}

void ShiftRegister::zeroOutputs() {
  for (byte i=0;i<SHIFT_DATA_BYTES;i++){
    shiftData[i] = 0;
  }
  shiftAllData();
}
```

**Comment by Sammy1Am** [comment]
Some re-org coming to the microcontroller code shortly that might make this easier.  Closing for now since it's been a while.

Specifically I've got some code in the experimental branch I'm brining over that detects board type (to some extent), and might make it easier to have STM32 working automatically.

**Pull request closed without merging**
